# Generated by Django 3.1 on 2020-09-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='m',
            field=models.URLField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Drama', 'Drama'), ('Action', 'Action'), ('Scifi', 'Scifi'), ('Thriller', 'Thriller'), ('Horror', 'Horror'), ('Anime', 'Anime')], max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
